In [1]:
import numpy as np

In [7]:
# first numpy array

In [2]:
first_np_array = np.array([1,2,3])

In [5]:
first_np_array

array([1, 2, 3])

In [6]:
# array with only zeroes

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# array with ones

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# array with empy values (numpy will fill elements by random values)

In [18]:
np.empty((3,5))

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])

In [19]:
np.empty((5,9))

array([[0.00000000e+000, 0.00000000e+000, 1.77863633e-322,
        0.00000000e+000, 0.00000000e+000, 1.73855115e-310,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [20]:
# creating an array with a range of values

In [22]:
arange = np.arange(12)

In [23]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
# reshaping array

In [27]:
arange.reshape((3,4)) # shallow copy is returned and can be stored in another object

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
# linespace for linearly equally spaced data elements

In [32]:
np.linspace(21,39,50) # forms an ap within the given range of elements

array([21.        , 21.36734694, 21.73469388, 22.10204082, 22.46938776,
       22.83673469, 23.20408163, 23.57142857, 23.93877551, 24.30612245,
       24.67346939, 25.04081633, 25.40816327, 25.7755102 , 26.14285714,
       26.51020408, 26.87755102, 27.24489796, 27.6122449 , 27.97959184,
       28.34693878, 28.71428571, 29.08163265, 29.44897959, 29.81632653,
       30.18367347, 30.55102041, 30.91836735, 31.28571429, 31.65306122,
       32.02040816, 32.3877551 , 32.75510204, 33.12244898, 33.48979592,
       33.85714286, 34.2244898 , 34.59183673, 34.95918367, 35.32653061,
       35.69387755, 36.06122449, 36.42857143, 36.79591837, 37.16326531,
       37.53061224, 37.89795918, 38.26530612, 38.63265306, 39.        ])

In [33]:
# 1 - D array

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.array([1,2,234,5,4,4,5,1,45])

array([  1,   2, 234,   5,   4,   4,   5,   1,  45])

In [39]:
np.array((1,2,4,4))

array([1, 2, 4, 4])

In [40]:
# 2 - D array

In [41]:
arange.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
arange.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
# 3 - D array

In [46]:
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])